import { ThemeConfig } from 'antd';

export const themeObject = (theme: any): ThemeConfig => {
  return {
    token: {
      colorBgContainer: `${theme?.color?.white}`,
      colorBgContainerDisabled: `${theme?.color?.grayLight}`,
      colorBgTextHover: `${theme?.color?.primaryLight}`,
      colorBorder: `${theme?.color?.primaryBorder}`,
      colorError: `${theme?.color?.danger}`,
      colorLink: `${theme?.color?.black}`,
      colorLinkActive: `${theme?.color?.primary}`,
      colorLinkHover: `${theme?.color?.primary}`,
      colorPrimary: `${theme?.color?.primary}`,
      colorPrimaryActive: `${theme?.color?.primary}`,
      colorPrimaryHover: `${theme?.color?.primary}`,
      colorText: `${theme?.color?.black}`,
      colorTextPlaceholder: `${theme?.color?.primaryLight}`,
      colorTextDisabled: `${theme?.color?.gray}`,
      borderRadius: 4,
      controlHeight: 36,
      controlHeightSM: 30,
      controlOutline: `${theme?.color?.transparent}`,
      fontSize: 14,
      fontFamily: `${theme?.font?.family?.GentiumBasic}`,
      fontSizeLG: 16,
      lineHeight: 1,
      controlPaddingHorizontal: 15,
      controlPaddingHorizontalSM: 10,
    },
    components: {
      Layout: {
        bodyBg: `${theme?.color?.background}`,
        footerBg: `${theme.color.white}`,
        footerPadding: '20px 30px',
        headerBg: `${theme.color.white}`,
        headerHeight: 48,
        headerPadding: '0 30px',
        siderBg: `${theme.color.white}`,
        triggerBg: `${theme.color.light}`,
        triggerColor: `${theme.color.black}`,
        triggerHeight: 56,
        colorText: `${theme?.color?.primary}`,
      },
      Menu: {
        darkItemBg: `${theme.color.white}`,
        darkItemColor: `${theme.color.primary}`,
        darkItemHoverBg: `${theme.color.grayLight}`,
        darkItemHoverColor: `${theme.color.primary}`,
        darkItemSelectedBg: `${theme.color.primaryLight}`,
        darkItemSelectedColor: `${theme.color.primary}`,
        darkItemDisabledColor: `${theme.color.grayLight}`,
        darkSubMenuItemBg: 'inherit',
        iconSize: 16,
        collapsedIconSize: 16,
        itemBorderRadius: 0,
        itemHeight: 42,
        itemMarginBlock: 0,
        itemMarginInline: 0,
        itemHoverBg: `${theme.color.secondaryLight}`,
        itemHoverColor: `${theme.color.secondary}`,
        itemSelectedColor: `${theme.font.color.secondary}`,
        itemSelectedBg: `${theme.color.secondaryLight}`,
        itemActiveBg: `${theme.color.secondaryLight}`,
      },
      Form: {
        itemMarginBottom: 0,
        labelColor: `${theme?.color?.primary}`,
        labelFontSize: 24,
        labelHeight: 30,
        verticalLabelPadding: '0 0 6px',
        colorError: `${theme?.color?.danger}`,
        lineHeight: 2,
      },
      Table: {
        // borderColor: `${theme?.color?.primaryLight}`,
        // cellFontSizeSM: 14,
        // headerBg: `${theme?.color?.primaryLight}`,
        headerColor: `${theme?.color?.primary}`,
        // rowHoverBg: `${theme?.color?.light}`,
        // headerBorderRadius: 6
        colorText: `${theme?.color?.primary}`,
        fontSize: 16,
        headerSplitColor: `${theme?.color?.transparent}`,
        headerBg: `${theme?.color?.inputBoxDisable}`,
      },
      Pagination: {
        itemSize: 30,
        itemSizeSM: 30,
        fontSize: 16,
      },
      Breadcrumb: {
        lastItemColor: `${theme?.color?.primary}`,
        itemColor: `${theme?.color?.primaryLight}`,
      },
      Input: {
        colorText: `${theme?.color?.primary}`,
        colorBgContainer: `${theme?.color?.inputBox}`,
        colorTextDisabled: `${theme?.color?.primary}`,
        colorBgContainerDisabled: `${theme?.color?.inputBoxDisable}`,
        inputFontSize: 20,
        inputFontSizeLG: 20,
        colorErrorText: `${theme?.color?.primary}`,
      },
      Modal: {
        fontFamily: `${theme?.font?.family?.GentiumBasic}`,
        titleColor: `${theme?.color?.primary}`,
        padding: 32,
      },
      Card: {
        padding: 8,
      },
      Tag: {
        fontSize: 16,
      },
      Select: {
        fontSize: 20,
        colorText: `${theme?.color?.primary}`,
        colorBgContainerDisabled: `${theme?.color?.inputBox}`,
        colorTextDisabled: `${theme?.color?.primary}`,
        fontSizeLG: 20,
        // optionActiveBg: `${theme?.color?.secondaryLight}`,
        optionSelectedBg: `${theme?.color?.secondaryLight}`,
      },
      Message: {
        fontFamily: `${theme?.font?.family?.GentiumBasic}`,
        motionDurationSlow: '0.9s',
      },
      Button: {
        fontSize: 16,
      },
      Tabs: {
        fontSize: 16,
        titleFontSize: 20,
      },
      Steps: {
        fontSize: 16,
        colorText: `${theme?.color?.primary}`,
        colorTextDescription: `${theme?.color?.primaryLight}`,
        colorTextDisabled: `${theme?.color?.primaryLight}`,
      },
    },
  };
};
